openapi: 3.0.3
info:
  title: 'Probing service API specifications'
  version: 1.0.0
  x-summary: 'Monitoring the E-Services status'
  description: >- 
   OpenAPI specification for state control of Public Administration e-services
  termsOfService: https://www.e-serviceurl-example.com/terms
  contact:
    name: contactToDefinePagoPa
    email: toDefinePagoPa@pagopa.it
  license:
    name: Interop's licence
    url: 'https://to-define/'
servers:
- url: 'https://to-define/'
  description: Development environment
tags:
  - name: InteropProbing
    description: >-
      Read data operations.

paths:
   '/interop/probing':
    get:
      summary: Monitoring the status of an e-services
      description: >-
        Checks an e-service status
      tags:
        - InteropProbing
      operationId: getEserviceStatus
      responses:
        '200':
          description: >-
            The e-service is up and running
        '500':                  
          description: >-
            A managed error has occured during the request elaboration
          content:                        
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
              example:
                type: string
                status: 500 
                title: 'Internal Server Error'
                detail: 'There is a problem processing the request on the server.'
                traceId: 'string'
                errors: [{'code':'000-1234', 'detail':'The server is currently down for maintenance. Please try again later.'}]

components:
  schemas:
    Problem:
      properties:
        type:
          description: URI reference of type definition
          type: string
        status:
          description: The HTTP status code generated by the origin server for this occurrence of the problem.
          example: 400
          exclusiveMaximum: true
          maximum: 600
          minimum: 100
          type: integer
          format: int64
        title:
          description: A short, summary of the problem type. Written in english and readable
          example: Service Unavailable
          maxLength: 64
          pattern: '^[ -~]{0,64}$'
          type: string
        detail:
          description: A human readable explanation of the problem.
          example: Request took too long to complete.
          maxLength: 4096
          pattern: '^.{0,1024}$'
          type: string
        traceId:
          type: string
          nullable: false
        errors:
          type: array
          minItems: 0
          items:
            $ref: '#/components/schemas/ProblemError'
      additionalProperties: false
      required:       
        - status
        - title
        - errors

    ProblemError:
      properties:
        code:
          description: Internal code of the error
          example: 123-4567
          minLength: 8
          maxLength: 8
          pattern: '^[0-9]{3}-[0-9]{4}$'
          type: string
        detail:
          description: A human readable explanation specific to this occurrence of the problem.
          example: Parameter not valid
          maxLength: 4096
          pattern: '^.{0,1024}$'
          type: string
      required:
        - code
        - detail   
